### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by shripriyaprabhakar**
@katie-truong @courtchao @cdl08001 hi all. I have added couple of tests using jest. Please review only index.test.js and database/index.js.

### CODE REVIEW

**Comment by cdl08001** [comment]
Hi @shripriyaprabhakar, I am reviewing this now.

**Comment by cdl08001** [comment]
Hey @shripriyaprabhakar, here are a few things I saw:

 - Some of your function names were a little unclear to me. For example, it's hard to know what 'idFunc' or 'randomDate' do without reading through the corresponding code. Maybe consider refactoring the names to represent what the functions do (like 'generateID' or 'getRandomDate'). I think that best practice is to use verb+noun combination when creating functions, but its just a suggestion.

- I noticed that there are several comments that just look like code, are you keeping this for any reason or is this something that can be deleted?

- I noticed that your 'deliveryCostFunc' function always returns 'Free Delivery'. Is this intended? 

- Double check your indentation and ESLint settings, it looks like a few things may have slipped through the cracks. For example (in database/index.js): 
  - Line 77 (check indentation)
  - Lines 86-92 (check indentation)

Great work!!

**Comment by shripriyaprabhakar** [comment]
Thanks for the review Cal. I will rename the functions as suggested. I left the commented code as is since I may require them once I do the server and client interactions. I will rectify the indentations. I was a bit sloppy about that. Thank you.

**Comment by shripriyaprabhakar** [comment]
@cdl08001 @courtchao @katie-truong I have made changes per feedback comments. Please review

**Pull request merged**
